// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from "react";
import Box from "@mui/material/Box";

// Example image imports (update paths as needed)
import coriander from "../../public/Coriander.png";
import cumin from "../../public/Cumin.png";
import turmeric from "../../public/Chili.png";
import redChilli from "../../public/Turmeric.png";
import DesiKing from "../../public/DesiKing.png";
import Image from "next/image";
import theme from "@/styles/theme";

export default function BrandHover() {
  return (
    <Box
      sx={{
        position: "relative",
        width: 400,
        height: 400,
        mx: "auto",
        backgroundColor: "inherit",
        borderRadius: 4,
        border: "2px solid",
        borderColor: "primary.main",
        overflow: "visible",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        transition: "height 1s ease, width 1s ease",
        "&:hover": {
          height: 800,
          width: 800,
          overflow: "auto",
        },
        "&:hover .product": {
          opacity: 1,
        },
        // On hover, move each product image outward
        "&:hover .product-top": {
          transform: "translate(-50%, -150%)",
        },
        "&:hover .product-left": {
          transform: "translate(-150%, -50%)",
        },
        "&:hover .product-right": {
          transform: "translate(50%, -50%)",
        },
        "&:hover .product-bottom": {
          transform: "translate(-50%, 50%)",
        },
      }}
    >
      <Box
        sx={{
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: "translate(-50%, -50%)",
          px: 4,
          py: 2,
          borderRadius: "50%",
          textAlign: "center",
          cursor: "pointer",
          fontWeight: "bold",
          zIndex: 2,
          height: 320,
          width: 320,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <Image src={DesiKing} alt="DesiKing" height={180} width={180} />
      </Box>
      {/* Product Images */}
      <Box
        className="product product-top"
        sx={{
          position: "absolute",
          top: "50%",
          left: "50%",
          width: 240,
          height: 240,
          transform: "translate(-50%, -50%)",
          opacity: 0,
          transition: "transform 1s cubic-bezier(.4,2,.6,1), opacity 1s",
          zIndex: 1,
        }}
      >
        <Image src={turmeric} alt="Turmeric" height={240} width={240} />
      </Box>
      <Box
        className="product product-right"
        sx={{
          position: "absolute",
          top: "50%",
          left: "50%",
          width: 240,
          height: 240,
          transform: "translate(-50%, -50%)",
          opacity: 0,
          transition: "transform 1s cubic-bezier(.4,2,.6,1), opacity 1s",
          zIndex: 1,
        }}
      >
        <Image src={redChilli} alt="Red Chilli" height={240} width={240} />
      </Box>
      <Box
        className="product product-left"
        sx={{
          position: "absolute",
          top: "50%",
          left: "50%",
          width: 240,
          height: 240,
          transform: "translate(-50%, -50%)",
          opacity: 0,
          transition: "transform 1s cubic-bezier(.4,2,.6,1), opacity 1s",
          zIndex: 1,
        }}
      >
        <Image src={cumin} alt="Cumin" height={240} width={240} />
      </Box>
      <Box
        className="product product-bottom"
        sx={{
          position: "absolute",
          top: "50%",
          left: "50%",
          width: 240,
          height: 240,
          transform: "translate(-50%, -50%)",
          opacity: 0,
          transition: "transform 1s cubic-bezier(.4,2,.6,1), opacity 1s",
          zIndex: 1,
        }}
      >
        <Image src={coriander} alt="Coriander" height={240} width={240} />
      </Box>
    </Box>
  );
}
